Vagrant.configure("2") do |config|
	# Ubuntu 14.04 Trusty Tahr 32-bit
	config.vm.box = "ubuntu/trusty32"

	# port forward 80 to 8080
	config.vm.network "forwarded_port", guest: 80, host: 8080

	# run bootstrap.sh when machine is ready
	config.vm.provision :shell, :path => "bootstrap.sh"
end